version: 2.1
sudo: required

jobs:
  build:
    docker:
      - image: circleci/node:7
        auth:
          username: $docker_username
          password: $docker_login
  # services:
  #   - docker
    steps:
      - checkout
      - run: docker build -t raudain123/docker-test-frontend -f Dockerfile.dev .
      - run: docker run npm raudain123/docker-test-frontend npm run test -- --coverage
