version: 2.1

jobs:
  build:
    docker:
      - image: cirlceci/node:7
  # services:
  #   - docker
    steps:
      - checkout
      - run: sudo systemctl start docker
      - run: docker build -t raudain123/docker-test-frontend -f Dockerfile.dev .
      - run: docker run npm raudain123/docker-test-frontend npm run test -- --coverage
