version: 2.1

jobs:
  test:
    working_directory: ~/usr/app
    docker:
      - image: circleci/node:latest
        auth:
          username: $docker_username
          password: $docker_login
    steps:
      - checkout
      - run: echo "This is a test"
      - run: npm install
      - run: npm test -- --coverage
  build:
    working_directory: ~/usr/app
    docker:
      - image: circleci/node:latest
        auth:
          username: $docker_username
          password: $docker_login
    steps:
      - checkout
      - run: echo "Test passed. Building app."
      - run: npm install
      - run: npm build

workflows:
  build_and_test:
    jobs:
      - test
      - build