version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:7
        auth:
          username: $docker_username
          password: $docker_login
  # services:
  #   - docker
    steps:
      - checkout
      # - run: sudo systemctl start docker
      - run: npm install
      # - run: docker build -t raudain123/docker-test-frontend .
      # - run: docker run raudain123/docker-test-frontend npm run test -- --coverage
      - run: npm test -- --coverage
